// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/mq/v1/message_queue.proto

package mqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PublishResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PublishBatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PublishRequest      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchReq) Reset() {
	*x = PublishBatchReq{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchReq) ProtoMessage() {}

func (x *PublishBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchReq.ProtoReflect.Descriptor instead.
func (*PublishBatchReq) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{2}
}

func (x *PublishBatchReq) GetMessages() []*PublishRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PublishBatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PublishResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResp) Reset() {
	*x = PublishBatchResp{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResp) ProtoMessage() {}

func (x *PublishBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResp.ProtoReflect.Descriptor instead.
func (*PublishBatchResp) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBatchResp) GetResults() []*PublishResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Max           int32                  `protobuf:"varint,5,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{4}
}

func (x *FetchRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FetchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *FetchRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FetchRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{5}
}

func (x *FetchResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Message) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Message) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{7}
}

func (x *CommitRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CommitRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommitRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *CommitRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{8}
}

func (x *CommitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *JoinRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *JoinRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenerationId  string                 `protobuf:"bytes,1,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{10}
}

func (x *JoinResponse) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GenerationId  string                 `protobuf:"bytes,3,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *HeartbeatRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *HeartbeatRequest) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RebalanceNeeded bool                   `protobuf:"varint,1,opt,name=rebalance_needed,json=rebalanceNeeded,proto3" json:"rebalance_needed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetRebalanceNeeded() bool {
	if x != nil {
		return x.RebalanceNeeded
	}
	return false
}

type AssignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GenerationId  string                 `protobuf:"bytes,3,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{13}
}

func (x *AssignRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AssignRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *AssignRequest) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

type AssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*PartitionAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignResponse) Reset() {
	*x = AssignResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignResponse) ProtoMessage() {}

func (x *AssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignResponse.ProtoReflect.Descriptor instead.
func (*AssignResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{14}
}

func (x *AssignResponse) GetAssignments() []*PartitionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type PartitionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	StartOffset   int64                  `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionAssignment) Reset() {
	*x = PartitionAssignment{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionAssignment) ProtoMessage() {}

func (x *PartitionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionAssignment.ProtoReflect.Descriptor instead.
func (*PartitionAssignment) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{15}
}

func (x *PartitionAssignment) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionAssignment) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{16}
}

func (x *LeaveRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *LeaveRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mq_v1_message_queue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_api_mq_v1_message_queue_proto_rawDescGZIP(), []int{17}
}

func (x *LeaveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_mq_v1_message_queue_proto protoreflect.FileDescriptor

const file_api_mq_v1_message_queue_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/mq/v1/message_queue.proto\x12\x05mq.v1\"R\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"G\n" +
	"\x0fPublishResponse\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"D\n" +
	"\x0fPublishBatchReq\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.mq.v1.PublishRequestR\bmessages\"D\n" +
	"\x10PublishBatchResp\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.mq.v1.PublishResponseR\aresults\"\x82\x01\n" +
	"\fFetchRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x05R\x03max\";\n" +
	"\rFetchResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.mq.v1.MessageR\bmessages\"\x8e\x01\n" +
	"\aMessage\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12!\n" +
	"\fpublished_at\x18\x05 \x01(\x03R\vpublishedAt\"q\n" +
	"\rCommitRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\" \n" +
	"\x0eCommitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"V\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\"3\n" +
	"\fJoinResponse\x12#\n" +
	"\rgeneration_id\x18\x01 \x01(\tR\fgenerationId\"j\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12#\n" +
	"\rgeneration_id\x18\x03 \x01(\tR\fgenerationId\">\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10rebalance_needed\x18\x01 \x01(\bR\x0frebalanceNeeded\"g\n" +
	"\rAssignRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12#\n" +
	"\rgeneration_id\x18\x03 \x01(\tR\fgenerationId\"N\n" +
	"\x0eAssignResponse\x12<\n" +
	"\vassignments\x18\x01 \x03(\v2\x1a.mq.v1.PartitionAssignmentR\vassignments\"V\n" +
	"\x13PartitionAssignment\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x03R\vstartOffset\"A\n" +
	"\fLeaveRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"\x1f\n" +
	"\rLeaveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xee\x03\n" +
	"\x13MessageQueueService\x128\n" +
	"\aPublish\x12\x15.mq.v1.PublishRequest\x1a\x16.mq.v1.PublishResponse\x12?\n" +
	"\fPublishBatch\x12\x16.mq.v1.PublishBatchReq\x1a\x17.mq.v1.PublishBatchResp\x122\n" +
	"\x05Fetch\x12\x13.mq.v1.FetchRequest\x1a\x14.mq.v1.FetchResponse\x12;\n" +
	"\fCommitOffset\x12\x14.mq.v1.CommitRequest\x1a\x15.mq.v1.CommitResponse\x124\n" +
	"\tJoinGroup\x12\x12.mq.v1.JoinRequest\x1a\x13.mq.v1.JoinResponse\x12>\n" +
	"\tHeartbeat\x12\x17.mq.v1.HeartbeatRequest\x1a\x18.mq.v1.HeartbeatResponse\x12<\n" +
	"\rGetAssignment\x12\x14.mq.v1.AssignRequest\x1a\x15.mq.v1.AssignResponse\x127\n" +
	"\n" +
	"LeaveGroup\x12\x13.mq.v1.LeaveRequest\x1a\x14.mq.v1.LeaveResponseB#Z!telemetry-streamer/api/mq/v1;mqv1b\x06proto3"

var (
	file_api_mq_v1_message_queue_proto_rawDescOnce sync.Once
	file_api_mq_v1_message_queue_proto_rawDescData []byte
)

func file_api_mq_v1_message_queue_proto_rawDescGZIP() []byte {
	file_api_mq_v1_message_queue_proto_rawDescOnce.Do(func() {
		file_api_mq_v1_message_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mq_v1_message_queue_proto_rawDesc), len(file_api_mq_v1_message_queue_proto_rawDesc)))
	})
	return file_api_mq_v1_message_queue_proto_rawDescData
}

var file_api_mq_v1_message_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_mq_v1_message_queue_proto_goTypes = []any{
	(*PublishRequest)(nil),      // 0: mq.v1.PublishRequest
	(*PublishResponse)(nil),     // 1: mq.v1.PublishResponse
	(*PublishBatchReq)(nil),     // 2: mq.v1.PublishBatchReq
	(*PublishBatchResp)(nil),    // 3: mq.v1.PublishBatchResp
	(*FetchRequest)(nil),        // 4: mq.v1.FetchRequest
	(*FetchResponse)(nil),       // 5: mq.v1.FetchResponse
	(*Message)(nil),             // 6: mq.v1.Message
	(*CommitRequest)(nil),       // 7: mq.v1.CommitRequest
	(*CommitResponse)(nil),      // 8: mq.v1.CommitResponse
	(*JoinRequest)(nil),         // 9: mq.v1.JoinRequest
	(*JoinResponse)(nil),        // 10: mq.v1.JoinResponse
	(*HeartbeatRequest)(nil),    // 11: mq.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 12: mq.v1.HeartbeatResponse
	(*AssignRequest)(nil),       // 13: mq.v1.AssignRequest
	(*AssignResponse)(nil),      // 14: mq.v1.AssignResponse
	(*PartitionAssignment)(nil), // 15: mq.v1.PartitionAssignment
	(*LeaveRequest)(nil),        // 16: mq.v1.LeaveRequest
	(*LeaveResponse)(nil),       // 17: mq.v1.LeaveResponse
}
var file_api_mq_v1_message_queue_proto_depIdxs = []int32{
	0,  // 0: mq.v1.PublishBatchReq.messages:type_name -> mq.v1.PublishRequest
	1,  // 1: mq.v1.PublishBatchResp.results:type_name -> mq.v1.PublishResponse
	6,  // 2: mq.v1.FetchResponse.messages:type_name -> mq.v1.Message
	15, // 3: mq.v1.AssignResponse.assignments:type_name -> mq.v1.PartitionAssignment
	0,  // 4: mq.v1.MessageQueueService.Publish:input_type -> mq.v1.PublishRequest
	2,  // 5: mq.v1.MessageQueueService.PublishBatch:input_type -> mq.v1.PublishBatchReq
	4,  // 6: mq.v1.MessageQueueService.Fetch:input_type -> mq.v1.FetchRequest
	7,  // 7: mq.v1.MessageQueueService.CommitOffset:input_type -> mq.v1.CommitRequest
	9,  // 8: mq.v1.MessageQueueService.JoinGroup:input_type -> mq.v1.JoinRequest
	11, // 9: mq.v1.MessageQueueService.Heartbeat:input_type -> mq.v1.HeartbeatRequest
	13, // 10: mq.v1.MessageQueueService.GetAssignment:input_type -> mq.v1.AssignRequest
	16, // 11: mq.v1.MessageQueueService.LeaveGroup:input_type -> mq.v1.LeaveRequest
	1,  // 12: mq.v1.MessageQueueService.Publish:output_type -> mq.v1.PublishResponse
	3,  // 13: mq.v1.MessageQueueService.PublishBatch:output_type -> mq.v1.PublishBatchResp
	5,  // 14: mq.v1.MessageQueueService.Fetch:output_type -> mq.v1.FetchResponse
	8,  // 15: mq.v1.MessageQueueService.CommitOffset:output_type -> mq.v1.CommitResponse
	10, // 16: mq.v1.MessageQueueService.JoinGroup:output_type -> mq.v1.JoinResponse
	12, // 17: mq.v1.MessageQueueService.Heartbeat:output_type -> mq.v1.HeartbeatResponse
	14, // 18: mq.v1.MessageQueueService.GetAssignment:output_type -> mq.v1.AssignResponse
	17, // 19: mq.v1.MessageQueueService.LeaveGroup:output_type -> mq.v1.LeaveResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_mq_v1_message_queue_proto_init() }
func file_api_mq_v1_message_queue_proto_init() {
	if File_api_mq_v1_message_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mq_v1_message_queue_proto_rawDesc), len(file_api_mq_v1_message_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mq_v1_message_queue_proto_goTypes,
		DependencyIndexes: file_api_mq_v1_message_queue_proto_depIdxs,
		MessageInfos:      file_api_mq_v1_message_queue_proto_msgTypes,
	}.Build()
	File_api_mq_v1_message_queue_proto = out.File
	file_api_mq_v1_message_queue_proto_goTypes = nil
	file_api_mq_v1_message_queue_proto_depIdxs = nil
}
