// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/mq/v1/message_queue.proto

package mqv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageQueueService_Publish_FullMethodName       = "/mq.v1.MessageQueueService/Publish"
	MessageQueueService_PublishBatch_FullMethodName  = "/mq.v1.MessageQueueService/PublishBatch"
	MessageQueueService_Fetch_FullMethodName         = "/mq.v1.MessageQueueService/Fetch"
	MessageQueueService_CommitOffset_FullMethodName  = "/mq.v1.MessageQueueService/CommitOffset"
	MessageQueueService_JoinGroup_FullMethodName     = "/mq.v1.MessageQueueService/JoinGroup"
	MessageQueueService_Heartbeat_FullMethodName     = "/mq.v1.MessageQueueService/Heartbeat"
	MessageQueueService_GetAssignment_FullMethodName = "/mq.v1.MessageQueueService/GetAssignment"
	MessageQueueService_LeaveGroup_FullMethodName    = "/mq.v1.MessageQueueService/LeaveGroup"
)

// MessageQueueServiceClient is the client API for MessageQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageQueueServiceClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	PublishBatch(ctx context.Context, in *PublishBatchReq, opts ...grpc.CallOption) (*PublishBatchResp, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	CommitOffset(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	JoinGroup(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetAssignment(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*AssignResponse, error)
	LeaveGroup(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
}

type messageQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueueServiceClient(cc grpc.ClientConnInterface) MessageQueueServiceClient {
	return &messageQueueServiceClient{cc}
}

func (c *messageQueueServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) PublishBatch(ctx context.Context, in *PublishBatchReq, opts ...grpc.CallOption) (*PublishBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishBatchResp)
	err := c.cc.Invoke(ctx, MessageQueueService_PublishBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) CommitOffset(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_CommitOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) JoinGroup(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) GetAssignment(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*AssignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_GetAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueServiceClient) LeaveGroup(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, MessageQueueService_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageQueueServiceServer is the server API for MessageQueueService service.
// All implementations must embed UnimplementedMessageQueueServiceServer
// for forward compatibility.
type MessageQueueServiceServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	PublishBatch(context.Context, *PublishBatchReq) (*PublishBatchResp, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	CommitOffset(context.Context, *CommitRequest) (*CommitResponse, error)
	JoinGroup(context.Context, *JoinRequest) (*JoinResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetAssignment(context.Context, *AssignRequest) (*AssignResponse, error)
	LeaveGroup(context.Context, *LeaveRequest) (*LeaveResponse, error)
	mustEmbedUnimplementedMessageQueueServiceServer()
}

// UnimplementedMessageQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageQueueServiceServer struct{}

func (UnimplementedMessageQueueServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedMessageQueueServiceServer) PublishBatch(context.Context, *PublishBatchReq) (*PublishBatchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishBatch not implemented")
}
func (UnimplementedMessageQueueServiceServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedMessageQueueServiceServer) CommitOffset(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitOffset not implemented")
}
func (UnimplementedMessageQueueServiceServer) JoinGroup(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedMessageQueueServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMessageQueueServiceServer) GetAssignment(context.Context, *AssignRequest) (*AssignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssignment not implemented")
}
func (UnimplementedMessageQueueServiceServer) LeaveGroup(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedMessageQueueServiceServer) mustEmbedUnimplementedMessageQueueServiceServer() {}
func (UnimplementedMessageQueueServiceServer) testEmbeddedByValue()                             {}

// UnsafeMessageQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageQueueServiceServer will
// result in compilation errors.
type UnsafeMessageQueueServiceServer interface {
	mustEmbedUnimplementedMessageQueueServiceServer()
}

func RegisterMessageQueueServiceServer(s grpc.ServiceRegistrar, srv MessageQueueServiceServer) {
	// If the following call panics, it indicates UnimplementedMessageQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageQueueService_ServiceDesc, srv)
}

func _MessageQueueService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_PublishBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).PublishBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_PublishBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).PublishBatch(ctx, req.(*PublishBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_CommitOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).CommitOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_CommitOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).CommitOffset(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).JoinGroup(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_GetAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).GetAssignment(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueueService_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServiceServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueueService_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServiceServer).LeaveGroup(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageQueueService_ServiceDesc is the grpc.ServiceDesc for MessageQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.v1.MessageQueueService",
	HandlerType: (*MessageQueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _MessageQueueService_Publish_Handler,
		},
		{
			MethodName: "PublishBatch",
			Handler:    _MessageQueueService_PublishBatch_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _MessageQueueService_Fetch_Handler,
		},
		{
			MethodName: "CommitOffset",
			Handler:    _MessageQueueService_CommitOffset_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _MessageQueueService_JoinGroup_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MessageQueueService_Heartbeat_Handler,
		},
		{
			MethodName: "GetAssignment",
			Handler:    _MessageQueueService_GetAssignment_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _MessageQueueService_LeaveGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mq/v1/message_queue.proto",
}
