version: "3.9"

services:
  telemetry-streamer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
