// Code generated by MockGen. DO NOT EDIT.
// Source: ../../ports/outbound/message_publisher.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	telemetry "telemetry-streamer/internal/domain/telemetry"
	outbound "telemetry-streamer/internal/ports/outbound"

	gomock "github.com/golang/mock/gomock"
)

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockMessagePublisher) Publish(ctx context.Context, reading telemetry.Reading) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, reading)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMessagePublisherMockRecorder) Publish(ctx, reading interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessagePublisher)(nil).Publish), ctx, reading)
}

// MockQueueMonitor is a mock of QueueMonitor interface.
type MockQueueMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMonitorMockRecorder
}

// MockQueueMonitorMockRecorder is the mock recorder for MockQueueMonitor.
type MockQueueMonitorMockRecorder struct {
	mock *MockQueueMonitor
}

// NewMockQueueMonitor creates a new mock instance.
func NewMockQueueMonitor(ctrl *gomock.Controller) *MockQueueMonitor {
	mock := &MockQueueMonitor{ctrl: ctrl}
	mock.recorder = &MockQueueMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueMonitor) EXPECT() *MockQueueMonitorMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockQueueMonitor) Health(ctx context.Context) outbound.QueueHealth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(outbound.QueueHealth)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockQueueMonitorMockRecorder) Health(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockQueueMonitor)(nil).Health), ctx)
}
