// Code generated by MockGen. DO NOT EDIT.
// Source: ../../ports/outbound/telemetry_reader.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	telemetry "telemetry-streamer/internal/domain/telemetry"

	gomock "github.com/golang/mock/gomock"
)

// MockTelemetryReader is a mock of TelemetryReader interface.
type MockTelemetryReader struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryReaderMockRecorder
}

// MockTelemetryReaderMockRecorder is the mock recorder for MockTelemetryReader.
type MockTelemetryReaderMockRecorder struct {
	mock *MockTelemetryReader
}

// NewMockTelemetryReader creates a new mock instance.
func NewMockTelemetryReader(ctrl *gomock.Controller) *MockTelemetryReader {
	mock := &MockTelemetryReader{ctrl: ctrl}
	mock.recorder = &MockTelemetryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryReader) EXPECT() *MockTelemetryReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockTelemetryReader) Read(ctx context.Context) (<-chan telemetry.Reading, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx)
	ret0, _ := ret[0].(<-chan telemetry.Reading)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockTelemetryReaderMockRecorder) Read(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockTelemetryReader)(nil).Read), ctx)
}
