// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryMessage is the wire format for a single telemetry sample (serialized as MQ PublishRequest.payload).
type TelemetryMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MetricName string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	GpuId      string                 `protobuf:"bytes,2,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`
	Device     string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Uuid       string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ModelName  string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	HostName   string                 `protobuf:"bytes,6,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Value      float64                `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`
	LabelsRaw  string                 `protobuf:"bytes,8,opt,name=labels_raw,json=labelsRaw,proto3" json:"labels_raw,omitempty"`
	// Nanoseconds since Unix epoch when this log was processed by the streamer.
	ProcessedAtUnixNano int64 `protobuf:"varint,9,opt,name=processed_at_unix_nano,json=processedAtUnixNano,proto3" json:"processed_at_unix_nano,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TelemetryMessage) Reset() {
	*x = TelemetryMessage{}
	mi := &file_api_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryMessage) ProtoMessage() {}

func (x *TelemetryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryMessage.ProtoReflect.Descriptor instead.
func (*TelemetryMessage) Descriptor() ([]byte, []int) {
	return file_api_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryMessage) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *TelemetryMessage) GetGpuId() string {
	if x != nil {
		return x.GpuId
	}
	return ""
}

func (x *TelemetryMessage) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TelemetryMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TelemetryMessage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TelemetryMessage) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *TelemetryMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryMessage) GetLabelsRaw() string {
	if x != nil {
		return x.LabelsRaw
	}
	return ""
}

func (x *TelemetryMessage) GetProcessedAtUnixNano() int64 {
	if x != nil {
		return x.ProcessedAtUnixNano
	}
	return 0
}

var File_api_telemetry_proto protoreflect.FileDescriptor

const file_api_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x13api/telemetry.proto\x12\ftelemetry.v1\"\x9c\x02\n" +
	"\x10TelemetryMessage\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x15\n" +
	"\x06gpu_id\x18\x02 \x01(\tR\x05gpuId\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12\x1b\n" +
	"\thost_name\x18\x06 \x01(\tR\bhostName\x12\x14\n" +
	"\x05value\x18\a \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"labels_raw\x18\b \x01(\tR\tlabelsRaw\x123\n" +
	"\x16processed_at_unix_nano\x18\t \x01(\x03R\x13processedAtUnixNanoB$Z\"telemetry-streamer/api;telemetryv1b\x06proto3"

var (
	file_api_telemetry_proto_rawDescOnce sync.Once
	file_api_telemetry_proto_rawDescData []byte
)

func file_api_telemetry_proto_rawDescGZIP() []byte {
	file_api_telemetry_proto_rawDescOnce.Do(func() {
		file_api_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telemetry_proto_rawDesc), len(file_api_telemetry_proto_rawDesc)))
	})
	return file_api_telemetry_proto_rawDescData
}

var file_api_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_telemetry_proto_goTypes = []any{
	(*TelemetryMessage)(nil), // 0: telemetry.v1.TelemetryMessage
}
var file_api_telemetry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_telemetry_proto_init() }
func file_api_telemetry_proto_init() {
	if File_api_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telemetry_proto_rawDesc), len(file_api_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_telemetry_proto_goTypes,
		DependencyIndexes: file_api_telemetry_proto_depIdxs,
		MessageInfos:      file_api_telemetry_proto_msgTypes,
	}.Build()
	File_api_telemetry_proto = out.File
	file_api_telemetry_proto_goTypes = nil
	file_api_telemetry_proto_depIdxs = nil
}
